"""modify parts table schema

Revision ID: 033fb0ba78c0
Revises: c4c43d86d700
Create Date: 2017-01-26 16:00:07.382820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033fb0ba78c0'
down_revision = 'c4c43d86d700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partsbatchtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_plate_barcode', sa.String(length=64), nullable=True),
    sa.Column('storage_location_id', sa.String(length=64), nullable=True),
    sa.Column('part_id', sa.String(length=64), nullable=True),
    sa.Column('part_number', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.Integer(), nullable=True),
    sa.Column('concatented_part_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partsbatchtable_batch_number'), 'partsbatchtable', ['batch_number'], unique=False)
    op.create_index(op.f('ix_partsbatchtable_concatented_part_id'), 'partsbatchtable', ['concatented_part_id'], unique=True)
    op.create_index(op.f('ix_partsbatchtable_part_id'), 'partsbatchtable', ['part_id'], unique=True)
    op.create_index(op.f('ix_partsbatchtable_part_number'), 'partsbatchtable', ['part_number'], unique=False)
    op.create_index(op.f('ix_partsbatchtable_storage_location_id'), 'partsbatchtable', ['storage_location_id'], unique=False)
    op.create_index(op.f('ix_partsbatchtable_storage_plate_barcode'), 'partsbatchtable', ['storage_plate_barcode'], unique=False)
    op.drop_index('ix_partstable_batch_number', table_name='partstable')
    op.drop_index('ix_partstable_storage_location_id', table_name='partstable')
    op.drop_index('ix_partstable_storage_plate_barcode', table_name='partstable')
    op.drop_column('partstable', 'storage_plate_barcode')
    op.drop_column('partstable', 'batch_number')
    op.drop_column('partstable', 'storage_location_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partstable', sa.Column('storage_location_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('partstable', sa.Column('batch_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('partstable', sa.Column('storage_plate_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_partstable_storage_plate_barcode', 'partstable', ['storage_plate_barcode'], unique=False)
    op.create_index('ix_partstable_storage_location_id', 'partstable', ['storage_location_id'], unique=False)
    op.create_index('ix_partstable_batch_number', 'partstable', ['batch_number'], unique=False)
    op.drop_index(op.f('ix_partsbatchtable_storage_plate_barcode'), table_name='partsbatchtable')
    op.drop_index(op.f('ix_partsbatchtable_storage_location_id'), table_name='partsbatchtable')
    op.drop_index(op.f('ix_partsbatchtable_part_number'), table_name='partsbatchtable')
    op.drop_index(op.f('ix_partsbatchtable_part_id'), table_name='partsbatchtable')
    op.drop_index(op.f('ix_partsbatchtable_concatented_part_id'), table_name='partsbatchtable')
    op.drop_index(op.f('ix_partsbatchtable_batch_number'), table_name='partsbatchtable')
    op.drop_table('partsbatchtable')
    # ### end Alembic commands ###
