"""added basic prefix

Revision ID: 03f014e8d128
Revises: fed23b3ce53a
Create Date: 2017-01-15 10:25:37.768783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03f014e8d128'
down_revision = 'fed23b3ce53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_buffer_plate_wells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('buffer_plate_well_id', sa.String(length=64), nullable=True),
    sa.Column('loading_volume', sa.Float(), nullable=True),
    sa.Column('buffer_plate_barcode', sa.String(length=64), nullable=True),
    sa.Column('buffer_plate_number', sa.Integer(), nullable=True),
    sa.Column('buffer_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_buffer_plate_wells_buffer_name'), 'basic_buffer_plate_wells', ['buffer_name'], unique=False)
    op.create_index(op.f('ix_basic_buffer_plate_wells_buffer_plate_barcode'), 'basic_buffer_plate_wells', ['buffer_plate_barcode'], unique=False)
    op.create_index(op.f('ix_basic_buffer_plate_wells_buffer_plate_number'), 'basic_buffer_plate_wells', ['buffer_plate_number'], unique=False)
    op.create_index(op.f('ix_basic_buffer_plate_wells_buffer_plate_well_id'), 'basic_buffer_plate_wells', ['buffer_plate_well_id'], unique=False)
    op.create_index(op.f('ix_basic_buffer_plate_wells_loading_volume'), 'basic_buffer_plate_wells', ['loading_volume'], unique=False)
    op.create_index(op.f('ix_basic_buffer_plate_wells_unique_job_id'), 'basic_buffer_plate_wells', ['unique_job_id'], unique=False)
    op.create_table('basic_clip_enzyme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('clip_well_id', sa.String(length=64), nullable=True),
    sa.Column('clip_barcode', sa.String(length=64), nullable=True),
    sa.Column('concatenated_clip_id', sa.String(length=64), nullable=True),
    sa.Column('clip_number', sa.Integer(), nullable=True),
    sa.Column('clip_batch_number', sa.Integer(), nullable=True),
    sa.Column('clip_plate_number', sa.Integer(), nullable=True),
    sa.Column('transfer_volume', sa.Integer(), nullable=True),
    sa.Column('enzyme_plate_barcode', sa.String(length=64), nullable=True),
    sa.Column('enzyme_plate_well_id', sa.String(length=64), nullable=True),
    sa.Column('enzyme_plate_number', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_clip_enzyme_clip_barcode'), 'basic_clip_enzyme', ['clip_barcode'], unique=False)
    op.create_index(op.f('ix_basic_clip_enzyme_clip_batch_number'), 'basic_clip_enzyme', ['clip_batch_number'], unique=False)
    op.create_index(op.f('ix_basic_clip_enzyme_clip_number'), 'basic_clip_enzyme', ['clip_number'], unique=False)
    op.create_index(op.f('ix_basic_clip_enzyme_clip_plate_number'), 'basic_clip_enzyme', ['clip_plate_number'], unique=False)
    op.create_index(op.f('ix_basic_clip_enzyme_clip_well_id'), 'basic_clip_enzyme', ['clip_well_id'], unique=False)
    op.create_index(op.f('ix_basic_clip_enzyme_concatenated_clip_id'), 'basic_clip_enzyme', ['concatenated_clip_id'], unique=False)
    op.create_index(op.f('ix_basic_clip_enzyme_enzyme_plate_barcode'), 'basic_clip_enzyme', ['enzyme_plate_barcode'], unique=False)
    op.create_index(op.f('ix_basic_clip_enzyme_enzyme_plate_number'), 'basic_clip_enzyme', ['enzyme_plate_number'], unique=False)
    op.create_index(op.f('ix_basic_clip_enzyme_enzyme_plate_well_id'), 'basic_clip_enzyme', ['enzyme_plate_well_id'], unique=False)
    op.create_index(op.f('ix_basic_clip_enzyme_transfer_volume'), 'basic_clip_enzyme', ['transfer_volume'], unique=False)
    op.create_index(op.f('ix_basic_clip_enzyme_unique_job_id'), 'basic_clip_enzyme', ['unique_job_id'], unique=False)
    op.create_table('basic_clip_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('part_id', sa.String(length=64), nullable=True),
    sa.Column('concatenated_part_id', sa.String(length=64), nullable=True),
    sa.Column('job_master_well_id', sa.String(length=64), nullable=True),
    sa.Column('job_master_barcode', sa.String(length=64), nullable=True),
    sa.Column('part_id_sample_number', sa.Integer(), nullable=True),
    sa.Column('clip_well_id', sa.String(length=64), nullable=True),
    sa.Column('clip_barcode', sa.String(length=64), nullable=True),
    sa.Column('concatenated_clip_id', sa.String(length=64), nullable=True),
    sa.Column('clip_number', sa.Integer(), nullable=True),
    sa.Column('clip_batch_number', sa.Integer(), nullable=True),
    sa.Column('destination_plate_number', sa.Integer(), nullable=True),
    sa.Column('transfer_volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_clip_list_clip_barcode'), 'basic_clip_list', ['clip_barcode'], unique=False)
    op.create_index(op.f('ix_basic_clip_list_clip_batch_number'), 'basic_clip_list', ['clip_batch_number'], unique=False)
    op.create_index(op.f('ix_basic_clip_list_clip_number'), 'basic_clip_list', ['clip_number'], unique=False)
    op.create_index(op.f('ix_basic_clip_list_clip_well_id'), 'basic_clip_list', ['clip_well_id'], unique=False)
    op.create_index(op.f('ix_basic_clip_list_concatenated_clip_id'), 'basic_clip_list', ['concatenated_clip_id'], unique=False)
    op.create_index(op.f('ix_basic_clip_list_concatenated_part_id'), 'basic_clip_list', ['concatenated_part_id'], unique=False)
    op.create_index(op.f('ix_basic_clip_list_destination_plate_number'), 'basic_clip_list', ['destination_plate_number'], unique=False)
    op.create_index(op.f('ix_basic_clip_list_job_master_barcode'), 'basic_clip_list', ['job_master_barcode'], unique=False)
    op.create_index(op.f('ix_basic_clip_list_job_master_well_id'), 'basic_clip_list', ['job_master_well_id'], unique=False)
    op.create_index(op.f('ix_basic_clip_list_part_id'), 'basic_clip_list', ['part_id'], unique=False)
    op.create_index(op.f('ix_basic_clip_list_part_id_sample_number'), 'basic_clip_list', ['part_id_sample_number'], unique=False)
    op.create_index(op.f('ix_basic_clip_list_transfer_volume'), 'basic_clip_list', ['transfer_volume'], unique=False)
    op.create_index(op.f('ix_basic_clip_list_unique_job_id'), 'basic_clip_list', ['unique_job_id'], unique=False)
    op.create_table('basic_clip_qc_fragment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('clip_well_id', sa.String(length=64), nullable=True),
    sa.Column('clip_barcode', sa.String(length=64), nullable=True),
    sa.Column('concatenated_clip_id', sa.String(length=64), nullable=True),
    sa.Column('clip_number', sa.Integer(), nullable=True),
    sa.Column('clip_batch_number', sa.Integer(), nullable=True),
    sa.Column('clip_plate_number', sa.Integer(), nullable=True),
    sa.Column('well_id_96', sa.String(length=64), nullable=True),
    sa.Column('well_id_384', sa.String(length=64), nullable=True),
    sa.Column('clip_qc_plate_number', sa.Integer(), nullable=True),
    sa.Column('clip_qc_barcode', sa.String(length=64), nullable=True),
    sa.Column('well_number_96', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_clip_qc_fragment_clip_barcode'), 'basic_clip_qc_fragment', ['clip_barcode'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_fragment_clip_batch_number'), 'basic_clip_qc_fragment', ['clip_batch_number'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_fragment_clip_number'), 'basic_clip_qc_fragment', ['clip_number'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_fragment_clip_plate_number'), 'basic_clip_qc_fragment', ['clip_plate_number'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_fragment_clip_qc_barcode'), 'basic_clip_qc_fragment', ['clip_qc_barcode'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_fragment_clip_qc_plate_number'), 'basic_clip_qc_fragment', ['clip_qc_plate_number'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_fragment_clip_well_id'), 'basic_clip_qc_fragment', ['clip_well_id'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_fragment_concatenated_clip_id'), 'basic_clip_qc_fragment', ['concatenated_clip_id'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_fragment_unique_job_id'), 'basic_clip_qc_fragment', ['unique_job_id'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_fragment_well_id_384'), 'basic_clip_qc_fragment', ['well_id_384'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_fragment_well_id_96'), 'basic_clip_qc_fragment', ['well_id_96'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_fragment_well_number_96'), 'basic_clip_qc_fragment', ['well_number_96'], unique=False)
    op.create_table('basic_clip_qc_plates_per_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('number_of_clip_plates', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_clip_qc_plates_per_job_number_of_clip_plates'), 'basic_clip_qc_plates_per_job', ['number_of_clip_plates'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_plates_per_job_unique_job_id'), 'basic_clip_qc_plates_per_job', ['unique_job_id'], unique=False)
    op.create_table('basic_job_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('part_id', sa.String(length=64), nullable=True),
    sa.Column('job_master_well_id', sa.String(length=64), nullable=True),
    sa.Column('job_master_barcode', sa.String(length=64), nullable=True),
    sa.Column('sample_number', sa.Integer(), nullable=True),
    sa.Column('uploaded_filename', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_job_master_job_master_barcode'), 'basic_job_master', ['job_master_barcode'], unique=False)
    op.create_index(op.f('ix_basic_job_master_job_master_well_id'), 'basic_job_master', ['job_master_well_id'], unique=False)
    op.create_index(op.f('ix_basic_job_master_part_id'), 'basic_job_master', ['part_id'], unique=False)
    op.create_index(op.f('ix_basic_job_master_sample_number'), 'basic_job_master', ['sample_number'], unique=False)
    op.create_index(op.f('ix_basic_job_master_unique_job_id'), 'basic_job_master', ['unique_job_id'], unique=False)
    op.create_index(op.f('ix_basic_job_master_uploaded_filename'), 'basic_job_master', ['uploaded_filename'], unique=False)
    op.create_table('basic_stitch_buffer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('stitch_well_id', sa.String(length=64), nullable=True),
    sa.Column('stitch_barcode', sa.String(length=64), nullable=True),
    sa.Column('stitch_id', sa.String(length=64), nullable=True),
    sa.Column('transfer_volume', sa.Integer(), nullable=True),
    sa.Column('enzyme_plate_barcode', sa.String(length=64), nullable=True),
    sa.Column('enzyme_plate_well_id', sa.String(length=64), nullable=True),
    sa.Column('enzyme_plate_number', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_stitch_buffer_enzyme_plate_barcode'), 'basic_stitch_buffer', ['enzyme_plate_barcode'], unique=False)
    op.create_index(op.f('ix_basic_stitch_buffer_enzyme_plate_number'), 'basic_stitch_buffer', ['enzyme_plate_number'], unique=False)
    op.create_index(op.f('ix_basic_stitch_buffer_enzyme_plate_well_id'), 'basic_stitch_buffer', ['enzyme_plate_well_id'], unique=False)
    op.create_index(op.f('ix_basic_stitch_buffer_stitch_barcode'), 'basic_stitch_buffer', ['stitch_barcode'], unique=False)
    op.create_index(op.f('ix_basic_stitch_buffer_stitch_id'), 'basic_stitch_buffer', ['stitch_id'], unique=False)
    op.create_index(op.f('ix_basic_stitch_buffer_stitch_well_id'), 'basic_stitch_buffer', ['stitch_well_id'], unique=False)
    op.create_index(op.f('ix_basic_stitch_buffer_transfer_volume'), 'basic_stitch_buffer', ['transfer_volume'], unique=False)
    op.create_index(op.f('ix_basic_stitch_buffer_unique_job_id'), 'basic_stitch_buffer', ['unique_job_id'], unique=False)
    op.create_table('basic_stitch_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('stitch_id', sa.String(length=64), nullable=True),
    sa.Column('clip_number', sa.Integer(), nullable=True),
    sa.Column('clip_batch_number', sa.Integer(), nullable=True),
    sa.Column('concatenated_clip_id', sa.String(length=64), nullable=True),
    sa.Column('clip_well_id', sa.String(length=64), nullable=True),
    sa.Column('clip_barcode', sa.String(length=64), nullable=True),
    sa.Column('stitch_well_id', sa.String(length=64), nullable=True),
    sa.Column('stitch_plate_barcode', sa.String(length=64), nullable=True),
    sa.Column('stitch_plate_number', sa.Integer(), nullable=True),
    sa.Column('transfer_volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_stitch_list_clip_barcode'), 'basic_stitch_list', ['clip_barcode'], unique=False)
    op.create_index(op.f('ix_basic_stitch_list_clip_batch_number'), 'basic_stitch_list', ['clip_batch_number'], unique=False)
    op.create_index(op.f('ix_basic_stitch_list_clip_number'), 'basic_stitch_list', ['clip_number'], unique=False)
    op.create_index(op.f('ix_basic_stitch_list_clip_well_id'), 'basic_stitch_list', ['clip_well_id'], unique=False)
    op.create_index(op.f('ix_basic_stitch_list_concatenated_clip_id'), 'basic_stitch_list', ['concatenated_clip_id'], unique=False)
    op.create_index(op.f('ix_basic_stitch_list_stitch_id'), 'basic_stitch_list', ['stitch_id'], unique=False)
    op.create_index(op.f('ix_basic_stitch_list_stitch_plate_barcode'), 'basic_stitch_list', ['stitch_plate_barcode'], unique=False)
    op.create_index(op.f('ix_basic_stitch_list_stitch_plate_number'), 'basic_stitch_list', ['stitch_plate_number'], unique=False)
    op.create_index(op.f('ix_basic_stitch_list_stitch_well_id'), 'basic_stitch_list', ['stitch_well_id'], unique=False)
    op.create_index(op.f('ix_basic_stitch_list_transfer_volume'), 'basic_stitch_list', ['transfer_volume'], unique=False)
    op.create_index(op.f('ix_basic_stitch_list_unique_job_id'), 'basic_stitch_list', ['unique_job_id'], unique=False)
    op.create_table('basic_unique_clip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('clip_number', sa.Integer(), nullable=True),
    sa.Column('part_1_id', sa.String(length=64), nullable=True),
    sa.Column('part_2_id', sa.String(length=64), nullable=True),
    sa.Column('part_3_id', sa.String(length=64), nullable=True),
    sa.Column('number_of_times_used', sa.Integer(), nullable=True),
    sa.Column('clip_batches_required', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_unique_clip_clip_batches_required'), 'basic_unique_clip', ['clip_batches_required'], unique=False)
    op.create_index(op.f('ix_basic_unique_clip_clip_number'), 'basic_unique_clip', ['clip_number'], unique=False)
    op.create_index(op.f('ix_basic_unique_clip_number_of_times_used'), 'basic_unique_clip', ['number_of_times_used'], unique=False)
    op.create_index(op.f('ix_basic_unique_clip_part_1_id'), 'basic_unique_clip', ['part_1_id'], unique=False)
    op.create_index(op.f('ix_basic_unique_clip_part_2_id'), 'basic_unique_clip', ['part_2_id'], unique=False)
    op.create_index(op.f('ix_basic_unique_clip_part_3_id'), 'basic_unique_clip', ['part_3_id'], unique=False)
    op.create_index(op.f('ix_basic_unique_clip_unique_job_id'), 'basic_unique_clip', ['unique_job_id'], unique=False)
    op.create_table('basic_unique_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('part_id', sa.String(length=64), nullable=True),
    sa.Column('samples_required', sa.Integer(), nullable=True),
    sa.Column('number_of_times_used', sa.Integer(), nullable=True),
    sa.Column('total_volume_required', sa.Integer(), nullable=True),
    sa.Column('volume_per_part', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_unique_part_number_of_times_used'), 'basic_unique_part', ['number_of_times_used'], unique=False)
    op.create_index(op.f('ix_basic_unique_part_part_id'), 'basic_unique_part', ['part_id'], unique=False)
    op.create_index(op.f('ix_basic_unique_part_samples_required'), 'basic_unique_part', ['samples_required'], unique=False)
    op.create_index(op.f('ix_basic_unique_part_total_volume_required'), 'basic_unique_part', ['total_volume_required'], unique=False)
    op.create_index(op.f('ix_basic_unique_part_unique_job_id'), 'basic_unique_part', ['unique_job_id'], unique=False)
    op.create_index(op.f('ix_basic_unique_part_volume_per_part'), 'basic_unique_part', ['volume_per_part'], unique=False)
    op.create_table('job_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_types_job_type'), 'job_types', ['job_type'], unique=True)
    op.drop_table('clip_qc_plates_per_job')
    op.drop_table('stitch_buffer')
    op.drop_table('clip_qc_fragment')
    op.drop_table('buffer_plate_wells')
    op.drop_table('clip_enzyme')
    op.drop_table('unique_part')
    op.drop_table('unique_clip')
    op.drop_table('job_master')
    op.drop_table('clip_list')
    op.drop_table('stitch_list')
    op.add_column('job_table', sa.Column('job_type', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_job_table_job_type'), 'job_table', ['job_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_table_job_type'), table_name='job_table')
    op.drop_column('job_table', 'job_type')
    op.create_table('stitch_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('stitch_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_batch_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('concatenated_clip_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_well_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('stitch_well_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('stitch_plate_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('stitch_plate_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transfer_volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stitch_list_pkey')
    )
    op.create_table('clip_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('concatenated_part_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('job_master_well_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('job_master_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_id_sample_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_well_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('concatenated_clip_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_batch_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('destination_plate_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transfer_volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clip_list_pkey')
    )
    op.create_table('job_master',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('job_master_well_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('job_master_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('sample_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_filename', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='job_master_pkey')
    )
    op.create_table('unique_clip',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('part_1_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_2_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_3_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('number_of_times_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_batches_required', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='unique_clip_pkey')
    )
    op.create_table('unique_part',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('samples_required', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_of_times_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_volume_required', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('volume_per_part', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='unique_part_pkey')
    )
    op.create_table('clip_enzyme',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_well_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('concatenated_clip_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_batch_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_plate_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transfer_volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('enzyme_plate_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('enzyme_plate_well_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('enzyme_plate_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clip_enzyme_pkey')
    )
    op.create_table('buffer_plate_wells',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('buffer_plate_well_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('loading_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('buffer_plate_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('buffer_plate_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buffer_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='buffer_plate_wells_pkey')
    )
    op.create_table('clip_qc_fragment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_well_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('concatenated_clip_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_batch_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_plate_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('well_id_96', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('well_id_384', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_qc_plate_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_qc_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('well_number_96', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clip_qc_fragment_pkey')
    )
    op.create_table('stitch_buffer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('stitch_well_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('stitch_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('stitch_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('transfer_volume', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('enzyme_plate_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('enzyme_plate_well_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('enzyme_plate_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stitch_buffer_pkey')
    )
    op.create_table('clip_qc_plates_per_job',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('number_of_clip_plates', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='clip_qc_plates_per_job_pkey')
    )
    op.drop_index(op.f('ix_job_types_job_type'), table_name='job_types')
    op.drop_table('job_types')
    op.drop_index(op.f('ix_basic_unique_part_volume_per_part'), table_name='basic_unique_part')
    op.drop_index(op.f('ix_basic_unique_part_unique_job_id'), table_name='basic_unique_part')
    op.drop_index(op.f('ix_basic_unique_part_total_volume_required'), table_name='basic_unique_part')
    op.drop_index(op.f('ix_basic_unique_part_samples_required'), table_name='basic_unique_part')
    op.drop_index(op.f('ix_basic_unique_part_part_id'), table_name='basic_unique_part')
    op.drop_index(op.f('ix_basic_unique_part_number_of_times_used'), table_name='basic_unique_part')
    op.drop_table('basic_unique_part')
    op.drop_index(op.f('ix_basic_unique_clip_unique_job_id'), table_name='basic_unique_clip')
    op.drop_index(op.f('ix_basic_unique_clip_part_3_id'), table_name='basic_unique_clip')
    op.drop_index(op.f('ix_basic_unique_clip_part_2_id'), table_name='basic_unique_clip')
    op.drop_index(op.f('ix_basic_unique_clip_part_1_id'), table_name='basic_unique_clip')
    op.drop_index(op.f('ix_basic_unique_clip_number_of_times_used'), table_name='basic_unique_clip')
    op.drop_index(op.f('ix_basic_unique_clip_clip_number'), table_name='basic_unique_clip')
    op.drop_index(op.f('ix_basic_unique_clip_clip_batches_required'), table_name='basic_unique_clip')
    op.drop_table('basic_unique_clip')
    op.drop_index(op.f('ix_basic_stitch_list_unique_job_id'), table_name='basic_stitch_list')
    op.drop_index(op.f('ix_basic_stitch_list_transfer_volume'), table_name='basic_stitch_list')
    op.drop_index(op.f('ix_basic_stitch_list_stitch_well_id'), table_name='basic_stitch_list')
    op.drop_index(op.f('ix_basic_stitch_list_stitch_plate_number'), table_name='basic_stitch_list')
    op.drop_index(op.f('ix_basic_stitch_list_stitch_plate_barcode'), table_name='basic_stitch_list')
    op.drop_index(op.f('ix_basic_stitch_list_stitch_id'), table_name='basic_stitch_list')
    op.drop_index(op.f('ix_basic_stitch_list_concatenated_clip_id'), table_name='basic_stitch_list')
    op.drop_index(op.f('ix_basic_stitch_list_clip_well_id'), table_name='basic_stitch_list')
    op.drop_index(op.f('ix_basic_stitch_list_clip_number'), table_name='basic_stitch_list')
    op.drop_index(op.f('ix_basic_stitch_list_clip_batch_number'), table_name='basic_stitch_list')
    op.drop_index(op.f('ix_basic_stitch_list_clip_barcode'), table_name='basic_stitch_list')
    op.drop_table('basic_stitch_list')
    op.drop_index(op.f('ix_basic_stitch_buffer_unique_job_id'), table_name='basic_stitch_buffer')
    op.drop_index(op.f('ix_basic_stitch_buffer_transfer_volume'), table_name='basic_stitch_buffer')
    op.drop_index(op.f('ix_basic_stitch_buffer_stitch_well_id'), table_name='basic_stitch_buffer')
    op.drop_index(op.f('ix_basic_stitch_buffer_stitch_id'), table_name='basic_stitch_buffer')
    op.drop_index(op.f('ix_basic_stitch_buffer_stitch_barcode'), table_name='basic_stitch_buffer')
    op.drop_index(op.f('ix_basic_stitch_buffer_enzyme_plate_well_id'), table_name='basic_stitch_buffer')
    op.drop_index(op.f('ix_basic_stitch_buffer_enzyme_plate_number'), table_name='basic_stitch_buffer')
    op.drop_index(op.f('ix_basic_stitch_buffer_enzyme_plate_barcode'), table_name='basic_stitch_buffer')
    op.drop_table('basic_stitch_buffer')
    op.drop_index(op.f('ix_basic_job_master_uploaded_filename'), table_name='basic_job_master')
    op.drop_index(op.f('ix_basic_job_master_unique_job_id'), table_name='basic_job_master')
    op.drop_index(op.f('ix_basic_job_master_sample_number'), table_name='basic_job_master')
    op.drop_index(op.f('ix_basic_job_master_part_id'), table_name='basic_job_master')
    op.drop_index(op.f('ix_basic_job_master_job_master_well_id'), table_name='basic_job_master')
    op.drop_index(op.f('ix_basic_job_master_job_master_barcode'), table_name='basic_job_master')
    op.drop_table('basic_job_master')
    op.drop_index(op.f('ix_basic_clip_qc_plates_per_job_unique_job_id'), table_name='basic_clip_qc_plates_per_job')
    op.drop_index(op.f('ix_basic_clip_qc_plates_per_job_number_of_clip_plates'), table_name='basic_clip_qc_plates_per_job')
    op.drop_table('basic_clip_qc_plates_per_job')
    op.drop_index(op.f('ix_basic_clip_qc_fragment_well_number_96'), table_name='basic_clip_qc_fragment')
    op.drop_index(op.f('ix_basic_clip_qc_fragment_well_id_96'), table_name='basic_clip_qc_fragment')
    op.drop_index(op.f('ix_basic_clip_qc_fragment_well_id_384'), table_name='basic_clip_qc_fragment')
    op.drop_index(op.f('ix_basic_clip_qc_fragment_unique_job_id'), table_name='basic_clip_qc_fragment')
    op.drop_index(op.f('ix_basic_clip_qc_fragment_concatenated_clip_id'), table_name='basic_clip_qc_fragment')
    op.drop_index(op.f('ix_basic_clip_qc_fragment_clip_well_id'), table_name='basic_clip_qc_fragment')
    op.drop_index(op.f('ix_basic_clip_qc_fragment_clip_qc_plate_number'), table_name='basic_clip_qc_fragment')
    op.drop_index(op.f('ix_basic_clip_qc_fragment_clip_qc_barcode'), table_name='basic_clip_qc_fragment')
    op.drop_index(op.f('ix_basic_clip_qc_fragment_clip_plate_number'), table_name='basic_clip_qc_fragment')
    op.drop_index(op.f('ix_basic_clip_qc_fragment_clip_number'), table_name='basic_clip_qc_fragment')
    op.drop_index(op.f('ix_basic_clip_qc_fragment_clip_batch_number'), table_name='basic_clip_qc_fragment')
    op.drop_index(op.f('ix_basic_clip_qc_fragment_clip_barcode'), table_name='basic_clip_qc_fragment')
    op.drop_table('basic_clip_qc_fragment')
    op.drop_index(op.f('ix_basic_clip_list_unique_job_id'), table_name='basic_clip_list')
    op.drop_index(op.f('ix_basic_clip_list_transfer_volume'), table_name='basic_clip_list')
    op.drop_index(op.f('ix_basic_clip_list_part_id_sample_number'), table_name='basic_clip_list')
    op.drop_index(op.f('ix_basic_clip_list_part_id'), table_name='basic_clip_list')
    op.drop_index(op.f('ix_basic_clip_list_job_master_well_id'), table_name='basic_clip_list')
    op.drop_index(op.f('ix_basic_clip_list_job_master_barcode'), table_name='basic_clip_list')
    op.drop_index(op.f('ix_basic_clip_list_destination_plate_number'), table_name='basic_clip_list')
    op.drop_index(op.f('ix_basic_clip_list_concatenated_part_id'), table_name='basic_clip_list')
    op.drop_index(op.f('ix_basic_clip_list_concatenated_clip_id'), table_name='basic_clip_list')
    op.drop_index(op.f('ix_basic_clip_list_clip_well_id'), table_name='basic_clip_list')
    op.drop_index(op.f('ix_basic_clip_list_clip_number'), table_name='basic_clip_list')
    op.drop_index(op.f('ix_basic_clip_list_clip_batch_number'), table_name='basic_clip_list')
    op.drop_index(op.f('ix_basic_clip_list_clip_barcode'), table_name='basic_clip_list')
    op.drop_table('basic_clip_list')
    op.drop_index(op.f('ix_basic_clip_enzyme_unique_job_id'), table_name='basic_clip_enzyme')
    op.drop_index(op.f('ix_basic_clip_enzyme_transfer_volume'), table_name='basic_clip_enzyme')
    op.drop_index(op.f('ix_basic_clip_enzyme_enzyme_plate_well_id'), table_name='basic_clip_enzyme')
    op.drop_index(op.f('ix_basic_clip_enzyme_enzyme_plate_number'), table_name='basic_clip_enzyme')
    op.drop_index(op.f('ix_basic_clip_enzyme_enzyme_plate_barcode'), table_name='basic_clip_enzyme')
    op.drop_index(op.f('ix_basic_clip_enzyme_concatenated_clip_id'), table_name='basic_clip_enzyme')
    op.drop_index(op.f('ix_basic_clip_enzyme_clip_well_id'), table_name='basic_clip_enzyme')
    op.drop_index(op.f('ix_basic_clip_enzyme_clip_plate_number'), table_name='basic_clip_enzyme')
    op.drop_index(op.f('ix_basic_clip_enzyme_clip_number'), table_name='basic_clip_enzyme')
    op.drop_index(op.f('ix_basic_clip_enzyme_clip_batch_number'), table_name='basic_clip_enzyme')
    op.drop_index(op.f('ix_basic_clip_enzyme_clip_barcode'), table_name='basic_clip_enzyme')
    op.drop_table('basic_clip_enzyme')
    op.drop_index(op.f('ix_basic_buffer_plate_wells_unique_job_id'), table_name='basic_buffer_plate_wells')
    op.drop_index(op.f('ix_basic_buffer_plate_wells_loading_volume'), table_name='basic_buffer_plate_wells')
    op.drop_index(op.f('ix_basic_buffer_plate_wells_buffer_plate_well_id'), table_name='basic_buffer_plate_wells')
    op.drop_index(op.f('ix_basic_buffer_plate_wells_buffer_plate_number'), table_name='basic_buffer_plate_wells')
    op.drop_index(op.f('ix_basic_buffer_plate_wells_buffer_plate_barcode'), table_name='basic_buffer_plate_wells')
    op.drop_index(op.f('ix_basic_buffer_plate_wells_buffer_name'), table_name='basic_buffer_plate_wells')
    op.drop_table('basic_buffer_plate_wells')
    # ### end Alembic commands ###
