"""added to batch table

Revision ID: 196f94f160e1
Revises: 5cd61afba32c
Create Date: 2017-01-28 18:43:54.863086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196f94f160e1'
down_revision = '5cd61afba32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_job_master', sa.Column('storage_location_id', sa.String(length=64), nullable=True))
    op.add_column('basic_job_master', sa.Column('storage_plate_barcode', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_basic_job_master_storage_location_id'), 'basic_job_master', ['storage_location_id'], unique=False)
    op.create_index(op.f('ix_basic_job_master_storage_plate_barcode'), 'basic_job_master', ['storage_plate_barcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_basic_job_master_storage_plate_barcode'), table_name='basic_job_master')
    op.drop_index(op.f('ix_basic_job_master_storage_location_id'), table_name='basic_job_master')
    op.drop_column('basic_job_master', 'storage_plate_barcode')
    op.drop_column('basic_job_master', 'storage_location_id')
    # ### end Alembic commands ###
