"""more ytk tables3

Revision ID: 1e3c17deb66b
Revises: f078a88d4092
Create Date: 2017-03-05 20:40:11.690716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3c17deb66b'
down_revision = 'f078a88d4092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ytk_job_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('part_id', sa.String(length=64), nullable=True),
    sa.Column('job_master_well_id', sa.String(length=64), nullable=True),
    sa.Column('job_master_barcode', sa.String(length=64), nullable=True),
    sa.Column('sample_number', sa.Integer(), nullable=True),
    sa.Column('uploaded_filename', sa.String(length=64), nullable=True),
    sa.Column('storage_plate_barcode', sa.String(length=64), nullable=True),
    sa.Column('storage_location_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ytk_job_master_job_master_barcode'), 'ytk_job_master', ['job_master_barcode'], unique=False)
    op.create_index(op.f('ix_ytk_job_master_job_master_well_id'), 'ytk_job_master', ['job_master_well_id'], unique=False)
    op.create_index(op.f('ix_ytk_job_master_part_id'), 'ytk_job_master', ['part_id'], unique=False)
    op.create_index(op.f('ix_ytk_job_master_sample_number'), 'ytk_job_master', ['sample_number'], unique=False)
    op.create_index(op.f('ix_ytk_job_master_storage_location_id'), 'ytk_job_master', ['storage_location_id'], unique=False)
    op.create_index(op.f('ix_ytk_job_master_storage_plate_barcode'), 'ytk_job_master', ['storage_plate_barcode'], unique=False)
    op.create_index(op.f('ix_ytk_job_master_unique_job_id'), 'ytk_job_master', ['unique_job_id'], unique=False)
    op.create_index(op.f('ix_ytk_job_master_uploaded_filename'), 'ytk_job_master', ['uploaded_filename'], unique=False)
    op.create_table('ytk_unique_clip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('clip_number', sa.Integer(), nullable=True),
    sa.Column('part_1_id', sa.String(length=64), nullable=True),
    sa.Column('part_2_id', sa.String(length=64), nullable=True),
    sa.Column('part_3_id', sa.String(length=64), nullable=True),
    sa.Column('part_4_id', sa.String(length=64), nullable=True),
    sa.Column('number_of_times_used', sa.Integer(), nullable=True),
    sa.Column('clip_batches_required', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ytk_unique_clip_clip_batches_required'), 'ytk_unique_clip', ['clip_batches_required'], unique=False)
    op.create_index(op.f('ix_ytk_unique_clip_clip_number'), 'ytk_unique_clip', ['clip_number'], unique=False)
    op.create_index(op.f('ix_ytk_unique_clip_number_of_times_used'), 'ytk_unique_clip', ['number_of_times_used'], unique=False)
    op.create_index(op.f('ix_ytk_unique_clip_part_1_id'), 'ytk_unique_clip', ['part_1_id'], unique=False)
    op.create_index(op.f('ix_ytk_unique_clip_part_2_id'), 'ytk_unique_clip', ['part_2_id'], unique=False)
    op.create_index(op.f('ix_ytk_unique_clip_part_3_id'), 'ytk_unique_clip', ['part_3_id'], unique=False)
    op.create_index(op.f('ix_ytk_unique_clip_part_4_id'), 'ytk_unique_clip', ['part_4_id'], unique=False)
    op.create_index(op.f('ix_ytk_unique_clip_unique_job_id'), 'ytk_unique_clip', ['unique_job_id'], unique=False)
    op.create_table('ytk_unique_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('part_id', sa.String(length=64), nullable=True),
    sa.Column('samples_required', sa.Integer(), nullable=True),
    sa.Column('number_of_times_used', sa.Integer(), nullable=True),
    sa.Column('total_volume_required', sa.Integer(), nullable=True),
    sa.Column('volume_per_part', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ytk_unique_part_number_of_times_used'), 'ytk_unique_part', ['number_of_times_used'], unique=False)
    op.create_index(op.f('ix_ytk_unique_part_part_id'), 'ytk_unique_part', ['part_id'], unique=False)
    op.create_index(op.f('ix_ytk_unique_part_samples_required'), 'ytk_unique_part', ['samples_required'], unique=False)
    op.create_index(op.f('ix_ytk_unique_part_total_volume_required'), 'ytk_unique_part', ['total_volume_required'], unique=False)
    op.create_index(op.f('ix_ytk_unique_part_unique_job_id'), 'ytk_unique_part', ['unique_job_id'], unique=False)
    op.create_index(op.f('ix_ytk_unique_part_volume_per_part'), 'ytk_unique_part', ['volume_per_part'], unique=False)
    op.drop_table('YTK_unique_part')
    op.drop_table('YTK_job_master')
    op.drop_table('YTK_unique_clip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('YTK_unique_clip',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"YTK_unique_clip_id_seq"\'::regclass)'), nullable=False),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('part_1_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_2_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_3_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_4_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('number_of_times_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_batches_required', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='YTK_unique_clip_pkey')
    )
    op.create_table('YTK_job_master',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"YTK_job_master_id_seq"\'::regclass)'), nullable=False),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('job_master_well_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('job_master_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('sample_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_filename', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('storage_plate_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('storage_location_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='YTK_job_master_pkey')
    )
    op.create_table('YTK_unique_part',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"YTK_unique_part_id_seq"\'::regclass)'), nullable=False),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('samples_required', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_of_times_used', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_volume_required', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('volume_per_part', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='YTK_unique_part_pkey')
    )
    op.drop_index(op.f('ix_ytk_unique_part_volume_per_part'), table_name='ytk_unique_part')
    op.drop_index(op.f('ix_ytk_unique_part_unique_job_id'), table_name='ytk_unique_part')
    op.drop_index(op.f('ix_ytk_unique_part_total_volume_required'), table_name='ytk_unique_part')
    op.drop_index(op.f('ix_ytk_unique_part_samples_required'), table_name='ytk_unique_part')
    op.drop_index(op.f('ix_ytk_unique_part_part_id'), table_name='ytk_unique_part')
    op.drop_index(op.f('ix_ytk_unique_part_number_of_times_used'), table_name='ytk_unique_part')
    op.drop_table('ytk_unique_part')
    op.drop_index(op.f('ix_ytk_unique_clip_unique_job_id'), table_name='ytk_unique_clip')
    op.drop_index(op.f('ix_ytk_unique_clip_part_4_id'), table_name='ytk_unique_clip')
    op.drop_index(op.f('ix_ytk_unique_clip_part_3_id'), table_name='ytk_unique_clip')
    op.drop_index(op.f('ix_ytk_unique_clip_part_2_id'), table_name='ytk_unique_clip')
    op.drop_index(op.f('ix_ytk_unique_clip_part_1_id'), table_name='ytk_unique_clip')
    op.drop_index(op.f('ix_ytk_unique_clip_number_of_times_used'), table_name='ytk_unique_clip')
    op.drop_index(op.f('ix_ytk_unique_clip_clip_number'), table_name='ytk_unique_clip')
    op.drop_index(op.f('ix_ytk_unique_clip_clip_batches_required'), table_name='ytk_unique_clip')
    op.drop_table('ytk_unique_clip')
    op.drop_index(op.f('ix_ytk_job_master_uploaded_filename'), table_name='ytk_job_master')
    op.drop_index(op.f('ix_ytk_job_master_unique_job_id'), table_name='ytk_job_master')
    op.drop_index(op.f('ix_ytk_job_master_storage_plate_barcode'), table_name='ytk_job_master')
    op.drop_index(op.f('ix_ytk_job_master_storage_location_id'), table_name='ytk_job_master')
    op.drop_index(op.f('ix_ytk_job_master_sample_number'), table_name='ytk_job_master')
    op.drop_index(op.f('ix_ytk_job_master_part_id'), table_name='ytk_job_master')
    op.drop_index(op.f('ix_ytk_job_master_job_master_well_id'), table_name='ytk_job_master')
    op.drop_index(op.f('ix_ytk_job_master_job_master_barcode'), table_name='ytk_job_master')
    op.drop_table('ytk_job_master')
    # ### end Alembic commands ###
