"""added more to clip id

Revision ID: 29b76ed5358c
Revises: f0b6be0058c0
Create Date: 2017-03-08 17:07:18.650675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b76ed5358c'
down_revision = 'f0b6be0058c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ytk_unique_clip', sa.Column('clip_id_job_id_no_batch_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_ytk_unique_clip_clip_id_job_id_no_batch_id'), 'ytk_unique_clip', ['clip_id_job_id_no_batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ytk_unique_clip_clip_id_job_id_no_batch_id'), table_name='ytk_unique_clip')
    op.drop_column('ytk_unique_clip', 'clip_id_job_id_no_batch_id')
    # ### end Alembic commands ###
