"""added clone plate

Revision ID: 2e35e3944322
Revises: 7fb1685fa05e
Create Date: 2017-01-18 10:19:21.881644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e35e3944322'
down_revision = '7fb1685fa05e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_stitch_clone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('clone_plate_well_id_96', sa.String(length=64), nullable=True),
    sa.Column('well_number_96', sa.Integer(), nullable=True),
    sa.Column('stitch_well_id', sa.String(length=64), nullable=True),
    sa.Column('stitch_plate_barcode', sa.String(length=64), nullable=True),
    sa.Column('stitch_plate_number', sa.Integer(), nullable=True),
    sa.Column('clone_plate_barcode', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_stitch_clone_clone_plate_barcode'), 'basic_stitch_clone', ['clone_plate_barcode'], unique=False)
    op.create_index(op.f('ix_basic_stitch_clone_clone_plate_well_id_96'), 'basic_stitch_clone', ['clone_plate_well_id_96'], unique=False)
    op.create_index(op.f('ix_basic_stitch_clone_stitch_plate_barcode'), 'basic_stitch_clone', ['stitch_plate_barcode'], unique=False)
    op.create_index(op.f('ix_basic_stitch_clone_stitch_plate_number'), 'basic_stitch_clone', ['stitch_plate_number'], unique=False)
    op.create_index(op.f('ix_basic_stitch_clone_stitch_well_id'), 'basic_stitch_clone', ['stitch_well_id'], unique=False)
    op.create_index(op.f('ix_basic_stitch_clone_unique_job_id'), 'basic_stitch_clone', ['unique_job_id'], unique=False)
    op.create_index(op.f('ix_basic_stitch_clone_well_number_96'), 'basic_stitch_clone', ['well_number_96'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_basic_stitch_clone_well_number_96'), table_name='basic_stitch_clone')
    op.drop_index(op.f('ix_basic_stitch_clone_unique_job_id'), table_name='basic_stitch_clone')
    op.drop_index(op.f('ix_basic_stitch_clone_stitch_well_id'), table_name='basic_stitch_clone')
    op.drop_index(op.f('ix_basic_stitch_clone_stitch_plate_number'), table_name='basic_stitch_clone')
    op.drop_index(op.f('ix_basic_stitch_clone_stitch_plate_barcode'), table_name='basic_stitch_clone')
    op.drop_index(op.f('ix_basic_stitch_clone_clone_plate_well_id_96'), table_name='basic_stitch_clone')
    op.drop_index(op.f('ix_basic_stitch_clone_clone_plate_barcode'), table_name='basic_stitch_clone')
    op.drop_table('basic_stitch_clone')
    # ### end Alembic commands ###
