"""added metrology types

Revision ID: 32603ed8f589
Revises: 79a1a8f844e4
Create Date: 2017-06-29 16:41:18.570675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32603ed8f589'
down_revision = '79a1a8f844e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrology_job_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('project_number', sa.String(length=64), nullable=True),
    sa.Column('job_integer', sa.Integer(), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrology_job_table_job_integer'), 'metrology_job_table', ['job_integer'], unique=False)
    op.create_index(op.f('ix_metrology_job_table_job_type'), 'metrology_job_table', ['job_type'], unique=False)
    op.create_index(op.f('ix_metrology_job_table_project_number'), 'metrology_job_table', ['project_number'], unique=False)
    op.create_index(op.f('ix_metrology_job_table_unique_job_id'), 'metrology_job_table', ['unique_job_id'], unique=True)
    op.create_table('metrology_job_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrology_job_types_job_type'), 'metrology_job_types', ['job_type'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrology_job_types_job_type'), table_name='metrology_job_types')
    op.drop_table('metrology_job_types')
    op.drop_index(op.f('ix_metrology_job_table_unique_job_id'), table_name='metrology_job_table')
    op.drop_index(op.f('ix_metrology_job_table_project_number'), table_name='metrology_job_table')
    op.drop_index(op.f('ix_metrology_job_table_job_type'), table_name='metrology_job_table')
    op.drop_index(op.f('ix_metrology_job_table_job_integer'), table_name='metrology_job_table')
    op.drop_table('metrology_job_table')
    # ### end Alembic commands ###
