"""empty message

Revision ID: 34b29c467b38
Revises: 4df5f985673c
Create Date: 2017-07-14 15:52:07.165049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b29c467b38'
down_revision = '4df5f985673c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tube_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=64), nullable=True),
    sa.Column('ref_number', sa.String(length=64), nullable=True),
    sa.Column('ldf_id', sa.String(length=64), nullable=True),
    sa.Column('ice_id', sa.String(length=64), nullable=True),
    sa.Column('dna_id', sa.String(length=64), nullable=True),
    sa.Column('supplier', sa.String(length=64), nullable=True),
    sa.Column('tube_barcode', sa.String(length=64), nullable=True),
    sa.Column('rack_barcode', sa.String(length=64), nullable=True),
    sa.Column('Position', sa.String(length=64), nullable=True),
    sa.Column('location_id1', sa.String(length=64), nullable=True),
    sa.Column('location_id2', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tube_storage_Position'), 'tube_storage', ['Position'], unique=False)
    op.create_index(op.f('ix_tube_storage_dna_id'), 'tube_storage', ['dna_id'], unique=False)
    op.create_index(op.f('ix_tube_storage_ice_id'), 'tube_storage', ['ice_id'], unique=False)
    op.create_index(op.f('ix_tube_storage_item_name'), 'tube_storage', ['item_name'], unique=False)
    op.create_index(op.f('ix_tube_storage_ldf_id'), 'tube_storage', ['ldf_id'], unique=False)
    op.create_index(op.f('ix_tube_storage_location_id1'), 'tube_storage', ['location_id1'], unique=False)
    op.create_index(op.f('ix_tube_storage_location_id2'), 'tube_storage', ['location_id2'], unique=False)
    op.create_index(op.f('ix_tube_storage_rack_barcode'), 'tube_storage', ['rack_barcode'], unique=False)
    op.create_index(op.f('ix_tube_storage_ref_number'), 'tube_storage', ['ref_number'], unique=False)
    op.create_index(op.f('ix_tube_storage_supplier'), 'tube_storage', ['supplier'], unique=False)
    op.create_index(op.f('ix_tube_storage_tube_barcode'), 'tube_storage', ['tube_barcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tube_storage_tube_barcode'), table_name='tube_storage')
    op.drop_index(op.f('ix_tube_storage_supplier'), table_name='tube_storage')
    op.drop_index(op.f('ix_tube_storage_ref_number'), table_name='tube_storage')
    op.drop_index(op.f('ix_tube_storage_rack_barcode'), table_name='tube_storage')
    op.drop_index(op.f('ix_tube_storage_location_id2'), table_name='tube_storage')
    op.drop_index(op.f('ix_tube_storage_location_id1'), table_name='tube_storage')
    op.drop_index(op.f('ix_tube_storage_ldf_id'), table_name='tube_storage')
    op.drop_index(op.f('ix_tube_storage_item_name'), table_name='tube_storage')
    op.drop_index(op.f('ix_tube_storage_ice_id'), table_name='tube_storage')
    op.drop_index(op.f('ix_tube_storage_dna_id'), table_name='tube_storage')
    op.drop_index(op.f('ix_tube_storage_Position'), table_name='tube_storage')
    op.drop_table('tube_storage')
    # ### end Alembic commands ###
