"""mistake with integer

Revision ID: 36f154b1159f
Revises: dc4b990068f2
Create Date: 2017-01-31 08:49:05.525155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f154b1159f'
down_revision = 'dc4b990068f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_virgin_design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stitch_id', sa.String(length=64), nullable=True),
    sa.Column('clip_id', sa.String(length=64), nullable=True),
    sa.Column('part_id', sa.String(length=64), nullable=True),
    sa.Column('part_name', sa.String(length=64), nullable=True),
    sa.Column('experiment_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_virgin_design_clip_id'), 'basic_virgin_design', ['clip_id'], unique=False)
    op.create_index(op.f('ix_basic_virgin_design_experiment_id'), 'basic_virgin_design', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_basic_virgin_design_part_id'), 'basic_virgin_design', ['part_id'], unique=False)
    op.create_index(op.f('ix_basic_virgin_design_part_name'), 'basic_virgin_design', ['part_name'], unique=False)
    op.create_index(op.f('ix_basic_virgin_design_stitch_id'), 'basic_virgin_design', ['stitch_id'], unique=False)
    op.drop_table('virgindesign')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virgindesign',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stitch_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_name', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='virgindesign_pkey')
    )
    op.drop_index(op.f('ix_basic_virgin_design_stitch_id'), table_name='basic_virgin_design')
    op.drop_index(op.f('ix_basic_virgin_design_part_name'), table_name='basic_virgin_design')
    op.drop_index(op.f('ix_basic_virgin_design_part_id'), table_name='basic_virgin_design')
    op.drop_index(op.f('ix_basic_virgin_design_experiment_id'), table_name='basic_virgin_design')
    op.drop_index(op.f('ix_basic_virgin_design_clip_id'), table_name='basic_virgin_design')
    op.drop_table('basic_virgin_design')
    # ### end Alembic commands ###
