"""added uniqueness to consumable

Revision ID: 3cf127046be8
Revises: 36f154b1159f
Create Date: 2017-02-20 12:31:19.209900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf127046be8'
down_revision = '36f154b1159f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_consumable_location_1', table_name='consumable')
    op.create_index(op.f('ix_consumable_location_1'), 'consumable', ['location_1'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumable_location_1'), table_name='consumable')
    op.create_index('ix_consumable_location_1', 'consumable', ['location_1'], unique=False)
    # ### end Alembic commands ###
