"""added assay plates to job

Revision ID: 3e8b21be1cf5
Revises: 566d4b4ebb6e
Create Date: 2017-06-30 16:55:57.902677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8b21be1cf5'
down_revision = '566d4b4ebb6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrology_plate_assigned_to_assay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_nice_name_id', sa.String(length=64), nullable=True),
    sa.Column('project_number', sa.String(length=64), nullable=True),
    sa.Column('metrology_unique_job_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrology_plate_assigned_to_assay_metrology_unique_job_id'), 'metrology_plate_assigned_to_assay', ['metrology_unique_job_id'], unique=False)
    op.create_index(op.f('ix_metrology_plate_assigned_to_assay_project_number'), 'metrology_plate_assigned_to_assay', ['project_number'], unique=False)
    op.create_index(op.f('ix_metrology_plate_assigned_to_assay_storage_nice_name_id'), 'metrology_plate_assigned_to_assay', ['storage_nice_name_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrology_plate_assigned_to_assay_storage_nice_name_id'), table_name='metrology_plate_assigned_to_assay')
    op.drop_index(op.f('ix_metrology_plate_assigned_to_assay_project_number'), table_name='metrology_plate_assigned_to_assay')
    op.drop_index(op.f('ix_metrology_plate_assigned_to_assay_metrology_unique_job_id'), table_name='metrology_plate_assigned_to_assay')
    op.drop_table('metrology_plate_assigned_to_assay')
    # ### end Alembic commands ###
