"""empty message

Revision ID: 4be59e16e00f
Revises: faa89e44e67e
Create Date: 2017-10-23 12:43:19.417656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4be59e16e00f'
down_revision = 'faa89e44e67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jmp_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=True),
    sa.Column('project_number', sa.String(length=64), nullable=True),
    sa.Column('job_number', sa.String(length=64), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jmp_tracker_filename'), 'jmp_tracker', ['filename'], unique=False)
    op.create_index(op.f('ix_jmp_tracker_item_description'), 'jmp_tracker', ['item_description'], unique=False)
    op.create_index(op.f('ix_jmp_tracker_job_number'), 'jmp_tracker', ['job_number'], unique=False)
    op.create_index(op.f('ix_jmp_tracker_project_number'), 'jmp_tracker', ['project_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jmp_tracker_project_number'), table_name='jmp_tracker')
    op.drop_index(op.f('ix_jmp_tracker_job_number'), table_name='jmp_tracker')
    op.drop_index(op.f('ix_jmp_tracker_item_description'), table_name='jmp_tracker')
    op.drop_index(op.f('ix_jmp_tracker_filename'), table_name='jmp_tracker')
    op.drop_table('jmp_tracker')
    # ### end Alembic commands ###
