"""added plate count

Revision ID: 4df5f985673c
Revises: 3e8b21be1cf5
Create Date: 2017-06-30 17:35:28.221301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df5f985673c'
down_revision = '3e8b21be1cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrology_plate_assigned_to_assay', sa.Column('plate_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_metrology_plate_assigned_to_assay_plate_count'), 'metrology_plate_assigned_to_assay', ['plate_count'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrology_plate_assigned_to_assay_plate_count'), table_name='metrology_plate_assigned_to_assay')
    op.drop_column('metrology_plate_assigned_to_assay', 'plate_count')
    # ### end Alembic commands ###
