"""removed uniqueness from batch table

Revision ID: 5cd61afba32c
Revises: 033fb0ba78c0
Create Date: 2017-01-28 18:10:41.276615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cd61afba32c'
down_revision = '033fb0ba78c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_partsbatchtable_part_id', table_name='partsbatchtable')
    op.create_index(op.f('ix_partsbatchtable_part_id'), 'partsbatchtable', ['part_id'], unique=False)
    op.drop_index('ix_partsbatchtable_concatented_part_id', table_name='partsbatchtable')
    op.drop_column('partsbatchtable', 'concatented_part_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partsbatchtable', sa.Column('concatented_part_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_partsbatchtable_concatented_part_id', 'partsbatchtable', ['concatented_part_id'], unique=True)
    op.drop_index(op.f('ix_partsbatchtable_part_id'), table_name='partsbatchtable')
    op.create_index('ix_partsbatchtable_part_id', 'partsbatchtable', ['part_id'], unique=True)
    # ### end Alembic commands ###
