"""more ytk tables

Revision ID: 61649bf931f1
Revises: 87e20657e329
Create Date: 2017-03-05 16:57:34.027388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61649bf931f1'
down_revision = '87e20657e329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('YTK__design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(length=64), nullable=True),
    sa.Column('part_id_sample_id', sa.Integer(), nullable=True),
    sa.Column('clip_id', sa.String(length=64), nullable=True),
    sa.Column('clip_id_batch_id', sa.Integer(), nullable=True),
    sa.Column('stitch_id', sa.String(length=64), nullable=True),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('unique_clip_number', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('uploaded_filename', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_YTK__design_clip_id'), 'YTK__design', ['clip_id'], unique=False)
    op.create_index(op.f('ix_YTK__design_clip_id_batch_id'), 'YTK__design', ['clip_id_batch_id'], unique=False)
    op.create_index(op.f('ix_YTK__design_level'), 'YTK__design', ['level'], unique=False)
    op.create_index(op.f('ix_YTK__design_part_id'), 'YTK__design', ['part_id'], unique=False)
    op.create_index(op.f('ix_YTK__design_part_id_sample_id'), 'YTK__design', ['part_id_sample_id'], unique=False)
    op.create_index(op.f('ix_YTK__design_stitch_id'), 'YTK__design', ['stitch_id'], unique=False)
    op.create_index(op.f('ix_YTK__design_unique_clip_number'), 'YTK__design', ['unique_clip_number'], unique=False)
    op.create_index(op.f('ix_YTK__design_unique_job_id'), 'YTK__design', ['unique_job_id'], unique=False)
    op.create_index(op.f('ix_YTK__design_uploaded_filename'), 'YTK__design', ['uploaded_filename'], unique=False)
    op.create_table('YTK_job_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('part_id', sa.String(length=64), nullable=True),
    sa.Column('job_master_well_id', sa.String(length=64), nullable=True),
    sa.Column('job_master_barcode', sa.String(length=64), nullable=True),
    sa.Column('sample_number', sa.Integer(), nullable=True),
    sa.Column('uploaded_filename', sa.String(length=64), nullable=True),
    sa.Column('storage_plate_barcode', sa.String(length=64), nullable=True),
    sa.Column('storage_location_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_YTK_job_master_job_master_barcode'), 'YTK_job_master', ['job_master_barcode'], unique=False)
    op.create_index(op.f('ix_YTK_job_master_job_master_well_id'), 'YTK_job_master', ['job_master_well_id'], unique=False)
    op.create_index(op.f('ix_YTK_job_master_part_id'), 'YTK_job_master', ['part_id'], unique=False)
    op.create_index(op.f('ix_YTK_job_master_sample_number'), 'YTK_job_master', ['sample_number'], unique=False)
    op.create_index(op.f('ix_YTK_job_master_storage_location_id'), 'YTK_job_master', ['storage_location_id'], unique=False)
    op.create_index(op.f('ix_YTK_job_master_storage_plate_barcode'), 'YTK_job_master', ['storage_plate_barcode'], unique=False)
    op.create_index(op.f('ix_YTK_job_master_unique_job_id'), 'YTK_job_master', ['unique_job_id'], unique=False)
    op.create_index(op.f('ix_YTK_job_master_uploaded_filename'), 'YTK_job_master', ['uploaded_filename'], unique=False)
    op.create_table('YTK_unique_clip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('clip_number', sa.Integer(), nullable=True),
    sa.Column('part_1_id', sa.String(length=64), nullable=True),
    sa.Column('part_2_id', sa.String(length=64), nullable=True),
    sa.Column('part_3_id', sa.String(length=64), nullable=True),
    sa.Column('part_4_id', sa.String(length=64), nullable=True),
    sa.Column('number_of_times_used', sa.Integer(), nullable=True),
    sa.Column('clip_batches_required', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_YTK_unique_clip_clip_batches_required'), 'YTK_unique_clip', ['clip_batches_required'], unique=False)
    op.create_index(op.f('ix_YTK_unique_clip_clip_number'), 'YTK_unique_clip', ['clip_number'], unique=False)
    op.create_index(op.f('ix_YTK_unique_clip_number_of_times_used'), 'YTK_unique_clip', ['number_of_times_used'], unique=False)
    op.create_index(op.f('ix_YTK_unique_clip_part_1_id'), 'YTK_unique_clip', ['part_1_id'], unique=False)
    op.create_index(op.f('ix_YTK_unique_clip_part_2_id'), 'YTK_unique_clip', ['part_2_id'], unique=False)
    op.create_index(op.f('ix_YTK_unique_clip_part_3_id'), 'YTK_unique_clip', ['part_3_id'], unique=False)
    op.create_index(op.f('ix_YTK_unique_clip_part_4_id'), 'YTK_unique_clip', ['part_4_id'], unique=False)
    op.create_index(op.f('ix_YTK_unique_clip_unique_job_id'), 'YTK_unique_clip', ['unique_job_id'], unique=False)
    op.create_table('YTK_unique_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('part_id', sa.String(length=64), nullable=True),
    sa.Column('samples_required', sa.Integer(), nullable=True),
    sa.Column('number_of_times_used', sa.Integer(), nullable=True),
    sa.Column('total_volume_required', sa.Integer(), nullable=True),
    sa.Column('volume_per_part', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_YTK_unique_part_number_of_times_used'), 'YTK_unique_part', ['number_of_times_used'], unique=False)
    op.create_index(op.f('ix_YTK_unique_part_part_id'), 'YTK_unique_part', ['part_id'], unique=False)
    op.create_index(op.f('ix_YTK_unique_part_samples_required'), 'YTK_unique_part', ['samples_required'], unique=False)
    op.create_index(op.f('ix_YTK_unique_part_total_volume_required'), 'YTK_unique_part', ['total_volume_required'], unique=False)
    op.create_index(op.f('ix_YTK_unique_part_unique_job_id'), 'YTK_unique_part', ['unique_job_id'], unique=False)
    op.create_index(op.f('ix_YTK_unique_part_volume_per_part'), 'YTK_unique_part', ['volume_per_part'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_YTK_unique_part_volume_per_part'), table_name='YTK_unique_part')
    op.drop_index(op.f('ix_YTK_unique_part_unique_job_id'), table_name='YTK_unique_part')
    op.drop_index(op.f('ix_YTK_unique_part_total_volume_required'), table_name='YTK_unique_part')
    op.drop_index(op.f('ix_YTK_unique_part_samples_required'), table_name='YTK_unique_part')
    op.drop_index(op.f('ix_YTK_unique_part_part_id'), table_name='YTK_unique_part')
    op.drop_index(op.f('ix_YTK_unique_part_number_of_times_used'), table_name='YTK_unique_part')
    op.drop_table('YTK_unique_part')
    op.drop_index(op.f('ix_YTK_unique_clip_unique_job_id'), table_name='YTK_unique_clip')
    op.drop_index(op.f('ix_YTK_unique_clip_part_4_id'), table_name='YTK_unique_clip')
    op.drop_index(op.f('ix_YTK_unique_clip_part_3_id'), table_name='YTK_unique_clip')
    op.drop_index(op.f('ix_YTK_unique_clip_part_2_id'), table_name='YTK_unique_clip')
    op.drop_index(op.f('ix_YTK_unique_clip_part_1_id'), table_name='YTK_unique_clip')
    op.drop_index(op.f('ix_YTK_unique_clip_number_of_times_used'), table_name='YTK_unique_clip')
    op.drop_index(op.f('ix_YTK_unique_clip_clip_number'), table_name='YTK_unique_clip')
    op.drop_index(op.f('ix_YTK_unique_clip_clip_batches_required'), table_name='YTK_unique_clip')
    op.drop_table('YTK_unique_clip')
    op.drop_index(op.f('ix_YTK_job_master_uploaded_filename'), table_name='YTK_job_master')
    op.drop_index(op.f('ix_YTK_job_master_unique_job_id'), table_name='YTK_job_master')
    op.drop_index(op.f('ix_YTK_job_master_storage_plate_barcode'), table_name='YTK_job_master')
    op.drop_index(op.f('ix_YTK_job_master_storage_location_id'), table_name='YTK_job_master')
    op.drop_index(op.f('ix_YTK_job_master_sample_number'), table_name='YTK_job_master')
    op.drop_index(op.f('ix_YTK_job_master_part_id'), table_name='YTK_job_master')
    op.drop_index(op.f('ix_YTK_job_master_job_master_well_id'), table_name='YTK_job_master')
    op.drop_index(op.f('ix_YTK_job_master_job_master_barcode'), table_name='YTK_job_master')
    op.drop_table('YTK_job_master')
    op.drop_index(op.f('ix_YTK__design_uploaded_filename'), table_name='YTK__design')
    op.drop_index(op.f('ix_YTK__design_unique_job_id'), table_name='YTK__design')
    op.drop_index(op.f('ix_YTK__design_unique_clip_number'), table_name='YTK__design')
    op.drop_index(op.f('ix_YTK__design_stitch_id'), table_name='YTK__design')
    op.drop_index(op.f('ix_YTK__design_part_id_sample_id'), table_name='YTK__design')
    op.drop_index(op.f('ix_YTK__design_part_id'), table_name='YTK__design')
    op.drop_index(op.f('ix_YTK__design_level'), table_name='YTK__design')
    op.drop_index(op.f('ix_YTK__design_clip_id_batch_id'), table_name='YTK__design')
    op.drop_index(op.f('ix_YTK__design_clip_id'), table_name='YTK__design')
    op.drop_table('YTK__design')
    # ### end Alembic commands ###
