"""updated joblength

Revision ID: 6d9db8212035
Revises: 03f014e8d128
Create Date: 2017-01-15 13:44:58.481126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9db8212035'
down_revision = '03f014e8d128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_length', sa.Column('stitch_length', sa.Integer(), nullable=True))
    op.add_column('job_length', sa.Column('stitch_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_job_length_stitch_length'), 'job_length', ['stitch_length'], unique=False)
    op.create_index(op.f('ix_job_length_stitch_number'), 'job_length', ['stitch_number'], unique=False)
    op.drop_index('ix_job_length_job_length', table_name='job_length')
    op.drop_column('job_length', 'job_length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_length', sa.Column('job_length', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_job_length_job_length', 'job_length', ['job_length'], unique=False)
    op.drop_index(op.f('ix_job_length_stitch_number'), table_name='job_length')
    op.drop_index(op.f('ix_job_length_stitch_length'), table_name='job_length')
    op.drop_column('job_length', 'stitch_number')
    op.drop_column('job_length', 'stitch_length')
    # ### end Alembic commands ###
