"""more ytk bufferenzyme

Revision ID: 7139eca901c0
Revises: ca1f78b3f79f
Create Date: 2017-03-07 16:58:55.313697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7139eca901c0'
down_revision = 'ca1f78b3f79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ytk_buffer_plate_wells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('buffer_plate_well_id', sa.String(length=64), nullable=True),
    sa.Column('loading_volume', sa.Float(), nullable=True),
    sa.Column('buffer_plate_barcode', sa.String(length=64), nullable=True),
    sa.Column('buffer_plate_number', sa.Integer(), nullable=True),
    sa.Column('buffer_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ytk_buffer_plate_wells_buffer_name'), 'ytk_buffer_plate_wells', ['buffer_name'], unique=False)
    op.create_index(op.f('ix_ytk_buffer_plate_wells_buffer_plate_barcode'), 'ytk_buffer_plate_wells', ['buffer_plate_barcode'], unique=False)
    op.create_index(op.f('ix_ytk_buffer_plate_wells_buffer_plate_number'), 'ytk_buffer_plate_wells', ['buffer_plate_number'], unique=False)
    op.create_index(op.f('ix_ytk_buffer_plate_wells_buffer_plate_well_id'), 'ytk_buffer_plate_wells', ['buffer_plate_well_id'], unique=False)
    op.create_index(op.f('ix_ytk_buffer_plate_wells_loading_volume'), 'ytk_buffer_plate_wells', ['loading_volume'], unique=False)
    op.create_index(op.f('ix_ytk_buffer_plate_wells_unique_job_id'), 'ytk_buffer_plate_wells', ['unique_job_id'], unique=False)
    op.create_table('ytk_clip_enzyme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('clip_well_id', sa.String(length=64), nullable=True),
    sa.Column('clip_barcode', sa.String(length=64), nullable=True),
    sa.Column('concatenated_clip_id', sa.String(length=64), nullable=True),
    sa.Column('clip_number', sa.Integer(), nullable=True),
    sa.Column('clip_batch_number', sa.Integer(), nullable=True),
    sa.Column('clip_plate_number', sa.Integer(), nullable=True),
    sa.Column('transfer_volume', sa.Integer(), nullable=True),
    sa.Column('enzyme_plate_barcode', sa.String(length=64), nullable=True),
    sa.Column('enzyme_plate_well_id', sa.String(length=64), nullable=True),
    sa.Column('enzyme_plate_number', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ytk_clip_enzyme_clip_barcode'), 'ytk_clip_enzyme', ['clip_barcode'], unique=False)
    op.create_index(op.f('ix_ytk_clip_enzyme_clip_batch_number'), 'ytk_clip_enzyme', ['clip_batch_number'], unique=False)
    op.create_index(op.f('ix_ytk_clip_enzyme_clip_number'), 'ytk_clip_enzyme', ['clip_number'], unique=False)
    op.create_index(op.f('ix_ytk_clip_enzyme_clip_plate_number'), 'ytk_clip_enzyme', ['clip_plate_number'], unique=False)
    op.create_index(op.f('ix_ytk_clip_enzyme_clip_well_id'), 'ytk_clip_enzyme', ['clip_well_id'], unique=False)
    op.create_index(op.f('ix_ytk_clip_enzyme_concatenated_clip_id'), 'ytk_clip_enzyme', ['concatenated_clip_id'], unique=False)
    op.create_index(op.f('ix_ytk_clip_enzyme_enzyme_plate_barcode'), 'ytk_clip_enzyme', ['enzyme_plate_barcode'], unique=False)
    op.create_index(op.f('ix_ytk_clip_enzyme_enzyme_plate_number'), 'ytk_clip_enzyme', ['enzyme_plate_number'], unique=False)
    op.create_index(op.f('ix_ytk_clip_enzyme_enzyme_plate_well_id'), 'ytk_clip_enzyme', ['enzyme_plate_well_id'], unique=False)
    op.create_index(op.f('ix_ytk_clip_enzyme_transfer_volume'), 'ytk_clip_enzyme', ['transfer_volume'], unique=False)
    op.create_index(op.f('ix_ytk_clip_enzyme_unique_job_id'), 'ytk_clip_enzyme', ['unique_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ytk_clip_enzyme_unique_job_id'), table_name='ytk_clip_enzyme')
    op.drop_index(op.f('ix_ytk_clip_enzyme_transfer_volume'), table_name='ytk_clip_enzyme')
    op.drop_index(op.f('ix_ytk_clip_enzyme_enzyme_plate_well_id'), table_name='ytk_clip_enzyme')
    op.drop_index(op.f('ix_ytk_clip_enzyme_enzyme_plate_number'), table_name='ytk_clip_enzyme')
    op.drop_index(op.f('ix_ytk_clip_enzyme_enzyme_plate_barcode'), table_name='ytk_clip_enzyme')
    op.drop_index(op.f('ix_ytk_clip_enzyme_concatenated_clip_id'), table_name='ytk_clip_enzyme')
    op.drop_index(op.f('ix_ytk_clip_enzyme_clip_well_id'), table_name='ytk_clip_enzyme')
    op.drop_index(op.f('ix_ytk_clip_enzyme_clip_plate_number'), table_name='ytk_clip_enzyme')
    op.drop_index(op.f('ix_ytk_clip_enzyme_clip_number'), table_name='ytk_clip_enzyme')
    op.drop_index(op.f('ix_ytk_clip_enzyme_clip_batch_number'), table_name='ytk_clip_enzyme')
    op.drop_index(op.f('ix_ytk_clip_enzyme_clip_barcode'), table_name='ytk_clip_enzyme')
    op.drop_table('ytk_clip_enzyme')
    op.drop_index(op.f('ix_ytk_buffer_plate_wells_unique_job_id'), table_name='ytk_buffer_plate_wells')
    op.drop_index(op.f('ix_ytk_buffer_plate_wells_loading_volume'), table_name='ytk_buffer_plate_wells')
    op.drop_index(op.f('ix_ytk_buffer_plate_wells_buffer_plate_well_id'), table_name='ytk_buffer_plate_wells')
    op.drop_index(op.f('ix_ytk_buffer_plate_wells_buffer_plate_number'), table_name='ytk_buffer_plate_wells')
    op.drop_index(op.f('ix_ytk_buffer_plate_wells_buffer_plate_barcode'), table_name='ytk_buffer_plate_wells')
    op.drop_index(op.f('ix_ytk_buffer_plate_wells_buffer_name'), table_name='ytk_buffer_plate_wells')
    op.drop_table('ytk_buffer_plate_wells')
    # ### end Alembic commands ###
