"""added dna sizes

Revision ID: 723a09ad094a
Revises: b936191eef4a
Create Date: 2017-06-01 14:48:16.431276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723a09ad094a'
down_revision = 'b936191eef4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_dna_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(length=64), nullable=True),
    sa.Column('enzyme', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('cargo_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_dna_sizes_cargo_number'), 'part_dna_sizes', ['cargo_number'], unique=False)
    op.create_index(op.f('ix_part_dna_sizes_enzyme'), 'part_dna_sizes', ['enzyme'], unique=False)
    op.create_index(op.f('ix_part_dna_sizes_part_id'), 'part_dna_sizes', ['part_id'], unique=False)
    op.create_index(op.f('ix_part_dna_sizes_size'), 'part_dna_sizes', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_part_dna_sizes_size'), table_name='part_dna_sizes')
    op.drop_index(op.f('ix_part_dna_sizes_part_id'), table_name='part_dna_sizes')
    op.drop_index(op.f('ix_part_dna_sizes_enzyme'), table_name='part_dna_sizes')
    op.drop_index(op.f('ix_part_dna_sizes_cargo_number'), table_name='part_dna_sizes')
    op.drop_table('part_dna_sizes')
    # ### end Alembic commands ###
