"""added basic stich clone qc columns

Revision ID: 79a1a8f844e4
Revises: e466f84812fa
Create Date: 2017-06-05 17:58:49.231834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a1a8f844e4'
down_revision = 'e466f84812fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_stitch_clone', sa.Column('stitch_qc1', sa.String(length=64), nullable=True))
    op.add_column('basic_stitch_clone', sa.Column('stitch_qc2', sa.String(length=64), nullable=True))
    op.add_column('basic_stitch_clone', sa.Column('stitch_qc3', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_basic_stitch_clone_stitch_qc1'), 'basic_stitch_clone', ['stitch_qc1'], unique=False)
    op.create_index(op.f('ix_basic_stitch_clone_stitch_qc2'), 'basic_stitch_clone', ['stitch_qc2'], unique=False)
    op.create_index(op.f('ix_basic_stitch_clone_stitch_qc3'), 'basic_stitch_clone', ['stitch_qc3'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_basic_stitch_clone_stitch_qc3'), table_name='basic_stitch_clone')
    op.drop_index(op.f('ix_basic_stitch_clone_stitch_qc2'), table_name='basic_stitch_clone')
    op.drop_index(op.f('ix_basic_stitch_clone_stitch_qc1'), table_name='basic_stitch_clone')
    op.drop_column('basic_stitch_clone', 'stitch_qc3')
    op.drop_column('basic_stitch_clone', 'stitch_qc2')
    op.drop_column('basic_stitch_clone', 'stitch_qc1')
    # ### end Alembic commands ###
