"""added parts table

Revision ID: 837d76119ac0
Revises: 
Create Date: 2017-01-15 08:19:34.672829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837d76119ac0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partstable', sa.Column('batch_number', sa.Integer(), nullable=True))
    op.add_column('partstable', sa.Column('composite_part', sa.Integer(), nullable=True))
    op.add_column('partstable', sa.Column('external_id', sa.String(length=64), nullable=True))
    op.add_column('partstable', sa.Column('part_method', sa.String(length=64), nullable=True))
    op.add_column('partstable', sa.Column('part_number', sa.Integer(), nullable=True))
    op.add_column('partstable', sa.Column('storage_location_id', sa.String(length=64), nullable=True))
    op.add_column('partstable', sa.Column('storage_plate_barcode', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_partstable_batch_number'), 'partstable', ['batch_number'], unique=False)
    op.create_index(op.f('ix_partstable_composite_part'), 'partstable', ['composite_part'], unique=False)
    op.create_index(op.f('ix_partstable_external_id'), 'partstable', ['external_id'], unique=False)
    op.create_index(op.f('ix_partstable_part_method'), 'partstable', ['part_method'], unique=False)
    op.create_index(op.f('ix_partstable_part_number'), 'partstable', ['part_number'], unique=False)
    op.create_index(op.f('ix_partstable_storage_location_id'), 'partstable', ['storage_location_id'], unique=False)
    op.create_index(op.f('ix_partstable_storage_plate_barcode'), 'partstable', ['storage_plate_barcode'], unique=False)
    op.drop_index('ix_partstable_master_plate_barcode', table_name='partstable')
    op.drop_index('ix_partstable_well_id', table_name='partstable')
    op.drop_column('partstable', 'master_plate_barcode')
    op.drop_column('partstable', 'well_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partstable', sa.Column('well_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('partstable', sa.Column('master_plate_barcode', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_partstable_well_id', 'partstable', ['well_id'], unique=False)
    op.create_index('ix_partstable_master_plate_barcode', 'partstable', ['master_plate_barcode'], unique=False)
    op.drop_index(op.f('ix_partstable_storage_plate_barcode'), table_name='partstable')
    op.drop_index(op.f('ix_partstable_storage_location_id'), table_name='partstable')
    op.drop_index(op.f('ix_partstable_part_number'), table_name='partstable')
    op.drop_index(op.f('ix_partstable_part_method'), table_name='partstable')
    op.drop_index(op.f('ix_partstable_external_id'), table_name='partstable')
    op.drop_index(op.f('ix_partstable_composite_part'), table_name='partstable')
    op.drop_index(op.f('ix_partstable_batch_number'), table_name='partstable')
    op.drop_column('partstable', 'storage_plate_barcode')
    op.drop_column('partstable', 'storage_location_id')
    op.drop_column('partstable', 'part_number')
    op.drop_column('partstable', 'part_method')
    op.drop_column('partstable', 'external_id')
    op.drop_column('partstable', 'composite_part')
    op.drop_column('partstable', 'batch_number')
    # ### end Alembic commands ###
