"""empty message

Revision ID: b936191eef4a
Revises: 67476b337962
Create Date: 2017-05-19 16:49:54.033586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b936191eef4a'
down_revision = '67476b337962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('partstable', 'sequence', existing_type=sa.VARCHAR(length=64), type_=sa.VARCHAR(length=256))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('partstable', 'sequence', existing_type=sa.VARCHAR(length=256), type_=sa.VARCHAR(length=64))

    # ### end Alembic commands ###
