"""more ytk clip list

Revision ID: ca1f78b3f79f
Revises: 1e3c17deb66b
Create Date: 2017-03-07 16:41:31.043267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1f78b3f79f'
down_revision = '1e3c17deb66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ytk_clip_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('part_id', sa.String(length=64), nullable=True),
    sa.Column('concatenated_part_id', sa.String(length=64), nullable=True),
    sa.Column('job_master_well_id', sa.String(length=64), nullable=True),
    sa.Column('job_master_barcode', sa.String(length=64), nullable=True),
    sa.Column('part_id_sample_number', sa.Integer(), nullable=True),
    sa.Column('clip_well_id', sa.String(length=64), nullable=True),
    sa.Column('clip_barcode', sa.String(length=64), nullable=True),
    sa.Column('concatenated_clip_id', sa.String(length=64), nullable=True),
    sa.Column('clip_number', sa.Integer(), nullable=True),
    sa.Column('clip_batch_number', sa.Integer(), nullable=True),
    sa.Column('destination_plate_number', sa.Integer(), nullable=True),
    sa.Column('transfer_volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ytk_clip_list_clip_barcode'), 'ytk_clip_list', ['clip_barcode'], unique=False)
    op.create_index(op.f('ix_ytk_clip_list_clip_batch_number'), 'ytk_clip_list', ['clip_batch_number'], unique=False)
    op.create_index(op.f('ix_ytk_clip_list_clip_number'), 'ytk_clip_list', ['clip_number'], unique=False)
    op.create_index(op.f('ix_ytk_clip_list_clip_well_id'), 'ytk_clip_list', ['clip_well_id'], unique=False)
    op.create_index(op.f('ix_ytk_clip_list_concatenated_clip_id'), 'ytk_clip_list', ['concatenated_clip_id'], unique=False)
    op.create_index(op.f('ix_ytk_clip_list_concatenated_part_id'), 'ytk_clip_list', ['concatenated_part_id'], unique=False)
    op.create_index(op.f('ix_ytk_clip_list_destination_plate_number'), 'ytk_clip_list', ['destination_plate_number'], unique=False)
    op.create_index(op.f('ix_ytk_clip_list_job_master_barcode'), 'ytk_clip_list', ['job_master_barcode'], unique=False)
    op.create_index(op.f('ix_ytk_clip_list_job_master_well_id'), 'ytk_clip_list', ['job_master_well_id'], unique=False)
    op.create_index(op.f('ix_ytk_clip_list_part_id'), 'ytk_clip_list', ['part_id'], unique=False)
    op.create_index(op.f('ix_ytk_clip_list_part_id_sample_number'), 'ytk_clip_list', ['part_id_sample_number'], unique=False)
    op.create_index(op.f('ix_ytk_clip_list_transfer_volume'), 'ytk_clip_list', ['transfer_volume'], unique=False)
    op.create_index(op.f('ix_ytk_clip_list_unique_job_id'), 'ytk_clip_list', ['unique_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ytk_clip_list_unique_job_id'), table_name='ytk_clip_list')
    op.drop_index(op.f('ix_ytk_clip_list_transfer_volume'), table_name='ytk_clip_list')
    op.drop_index(op.f('ix_ytk_clip_list_part_id_sample_number'), table_name='ytk_clip_list')
    op.drop_index(op.f('ix_ytk_clip_list_part_id'), table_name='ytk_clip_list')
    op.drop_index(op.f('ix_ytk_clip_list_job_master_well_id'), table_name='ytk_clip_list')
    op.drop_index(op.f('ix_ytk_clip_list_job_master_barcode'), table_name='ytk_clip_list')
    op.drop_index(op.f('ix_ytk_clip_list_destination_plate_number'), table_name='ytk_clip_list')
    op.drop_index(op.f('ix_ytk_clip_list_concatenated_part_id'), table_name='ytk_clip_list')
    op.drop_index(op.f('ix_ytk_clip_list_concatenated_clip_id'), table_name='ytk_clip_list')
    op.drop_index(op.f('ix_ytk_clip_list_clip_well_id'), table_name='ytk_clip_list')
    op.drop_index(op.f('ix_ytk_clip_list_clip_number'), table_name='ytk_clip_list')
    op.drop_index(op.f('ix_ytk_clip_list_clip_batch_number'), table_name='ytk_clip_list')
    op.drop_index(op.f('ix_ytk_clip_list_clip_barcode'), table_name='ytk_clip_list')
    op.drop_table('ytk_clip_list')
    # ### end Alembic commands ###
