"""added basic qc filesize

Revision ID: d08ff74c1574
Revises: 723a09ad094a
Create Date: 2017-06-01 16:59:17.495417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08ff74c1574'
down_revision = '723a09ad094a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_clip_qc_part_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clip_id', sa.String(length=64), nullable=True),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('cargo_size', sa.String(length=64), nullable=True),
    sa.Column('other_sizes', sa.String(length=64), nullable=True),
    sa.Column('uploaded_filename', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basic_clip_qc_part_sizes_cargo_size'), 'basic_clip_qc_part_sizes', ['cargo_size'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_part_sizes_clip_id'), 'basic_clip_qc_part_sizes', ['clip_id'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_part_sizes_other_sizes'), 'basic_clip_qc_part_sizes', ['other_sizes'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_part_sizes_unique_job_id'), 'basic_clip_qc_part_sizes', ['unique_job_id'], unique=False)
    op.create_index(op.f('ix_basic_clip_qc_part_sizes_uploaded_filename'), 'basic_clip_qc_part_sizes', ['uploaded_filename'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_basic_clip_qc_part_sizes_uploaded_filename'), table_name='basic_clip_qc_part_sizes')
    op.drop_index(op.f('ix_basic_clip_qc_part_sizes_unique_job_id'), table_name='basic_clip_qc_part_sizes')
    op.drop_index(op.f('ix_basic_clip_qc_part_sizes_other_sizes'), table_name='basic_clip_qc_part_sizes')
    op.drop_index(op.f('ix_basic_clip_qc_part_sizes_clip_id'), table_name='basic_clip_qc_part_sizes')
    op.drop_index(op.f('ix_basic_clip_qc_part_sizes_cargo_size'), table_name='basic_clip_qc_part_sizes')
    op.drop_table('basic_clip_qc_part_sizes')
    # ### end Alembic commands ###
