"""added db text

Revision ID: e889ad0ea867
Revises: 34b29c467b38
Create Date: 2017-07-15 11:29:18.465300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e889ad0ea867'
down_revision = '34b29c467b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tube_storage', sa.Column('item_description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_tube_storage_item_description'), 'tube_storage', ['item_description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tube_storage_item_description'), table_name='tube_storage')
    op.drop_column('tube_storage', 'item_description')
    # ### end Alembic commands ###
