"""added column

Revision ID: ed1caa589999
Revises: e292a21703ca
Create Date: 2017-06-29 18:19:35.630100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed1caa589999'
down_revision = 'e292a21703ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrology_plate_types', sa.Column('plate_type', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_metrology_plate_types_plate_type'), 'metrology_plate_types', ['plate_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrology_plate_types_plate_type'), table_name='metrology_plate_types')
    op.drop_column('metrology_plate_types', 'plate_type')
    # ### end Alembic commands ###
