"""more ytk tables2

Revision ID: f078a88d4092
Revises: 61649bf931f1
Create Date: 2017-03-05 16:59:12.723545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f078a88d4092'
down_revision = '61649bf931f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ytk_design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(length=64), nullable=True),
    sa.Column('part_id_sample_id', sa.Integer(), nullable=True),
    sa.Column('clip_id', sa.String(length=64), nullable=True),
    sa.Column('clip_id_batch_id', sa.Integer(), nullable=True),
    sa.Column('stitch_id', sa.String(length=64), nullable=True),
    sa.Column('unique_job_id', sa.String(length=64), nullable=True),
    sa.Column('unique_clip_number', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('uploaded_filename', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ytk_design_clip_id'), 'ytk_design', ['clip_id'], unique=False)
    op.create_index(op.f('ix_ytk_design_clip_id_batch_id'), 'ytk_design', ['clip_id_batch_id'], unique=False)
    op.create_index(op.f('ix_ytk_design_level'), 'ytk_design', ['level'], unique=False)
    op.create_index(op.f('ix_ytk_design_part_id'), 'ytk_design', ['part_id'], unique=False)
    op.create_index(op.f('ix_ytk_design_part_id_sample_id'), 'ytk_design', ['part_id_sample_id'], unique=False)
    op.create_index(op.f('ix_ytk_design_stitch_id'), 'ytk_design', ['stitch_id'], unique=False)
    op.create_index(op.f('ix_ytk_design_unique_clip_number'), 'ytk_design', ['unique_clip_number'], unique=False)
    op.create_index(op.f('ix_ytk_design_unique_job_id'), 'ytk_design', ['unique_job_id'], unique=False)
    op.create_index(op.f('ix_ytk_design_uploaded_filename'), 'ytk_design', ['uploaded_filename'], unique=False)
    op.drop_table('YTK__design')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('YTK__design',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"YTK__design_id_seq"\'::regclass)'), nullable=False),
    sa.Column('part_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('part_id_sample_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clip_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('clip_id_batch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stitch_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('unique_job_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('unique_clip_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_filename', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='YTK__design_pkey')
    )
    op.drop_index(op.f('ix_ytk_design_uploaded_filename'), table_name='ytk_design')
    op.drop_index(op.f('ix_ytk_design_unique_job_id'), table_name='ytk_design')
    op.drop_index(op.f('ix_ytk_design_unique_clip_number'), table_name='ytk_design')
    op.drop_index(op.f('ix_ytk_design_stitch_id'), table_name='ytk_design')
    op.drop_index(op.f('ix_ytk_design_part_id_sample_id'), table_name='ytk_design')
    op.drop_index(op.f('ix_ytk_design_part_id'), table_name='ytk_design')
    op.drop_index(op.f('ix_ytk_design_level'), table_name='ytk_design')
    op.drop_index(op.f('ix_ytk_design_clip_id_batch_id'), table_name='ytk_design')
    op.drop_index(op.f('ix_ytk_design_clip_id'), table_name='ytk_design')
    op.drop_table('ytk_design')
    # ### end Alembic commands ###
