"""added more to clip clone plate

Revision ID: f0b6be0058c0
Revises: 64d3c7b6d300
Create Date: 2017-03-08 10:31:28.890142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b6be0058c0'
down_revision = '64d3c7b6d300'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ytk_clip_clone', sa.Column('clip_id_job_id', sa.String(length=64), nullable=True))
    op.add_column('ytk_clip_clone', sa.Column('clip_id_job_id_no_batch_id', sa.String(length=64), nullable=True))
    op.add_column('ytk_clip_clone', sa.Column('clip_id_no_batch', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_ytk_clip_clone_clip_id_job_id'), 'ytk_clip_clone', ['clip_id_job_id'], unique=False)
    op.create_index(op.f('ix_ytk_clip_clone_clip_id_job_id_no_batch_id'), 'ytk_clip_clone', ['clip_id_job_id_no_batch_id'], unique=False)
    op.create_index(op.f('ix_ytk_clip_clone_clip_id_no_batch'), 'ytk_clip_clone', ['clip_id_no_batch'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ytk_clip_clone_clip_id_no_batch'), table_name='ytk_clip_clone')
    op.drop_index(op.f('ix_ytk_clip_clone_clip_id_job_id_no_batch_id'), table_name='ytk_clip_clone')
    op.drop_index(op.f('ix_ytk_clip_clone_clip_id_job_id'), table_name='ytk_clip_clone')
    op.drop_column('ytk_clip_clone', 'clip_id_no_batch')
    op.drop_column('ytk_clip_clone', 'clip_id_job_id_no_batch_id')
    op.drop_column('ytk_clip_clone', 'clip_id_job_id')
    # ### end Alembic commands ###
