"""empty message

Revision ID: faa89e44e67e
Revises: e889ad0ea867
Create Date: 2017-10-09 17:01:17.113125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa89e44e67e'
down_revision = 'e889ad0ea867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ytk_design', sa.Column('clip_id_sample_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ytk_design_clip_id_sample_id'), 'ytk_design', ['clip_id_sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ytk_design_clip_id_sample_id'), table_name='ytk_design')
    op.drop_column('ytk_design', 'clip_id_sample_id')
    # ### end Alembic commands ###
